---
ID: "4a5beb56-09ec-4b9e-a0e2-ebce2124d40b"
Parent: "ccd5e896-36a1-4eac-9a7f-c2aa23ed8080"
Template: "ccd5e896-36a1-4eac-9a7f-c2aa23ed8080"
Path: /sitecore/templates/Modules/PowerShell DataSync/Import Script Library/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/escalator_up.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190109T173419Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
